config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :comments, except: :show
    resources :project_conversation_histories, only: :show
  end
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :project
  belongs_to :user

  after_create :create_conversation_history_for_comment_create
  after_update :create_conversation_history_for_comment_update
  after_destroy :create_conversation_history_for_comment_delete

  private

  def create_conversation_history_for_comment_create
    project.project_conversation_histories.create!(
      history_type: ProjectConversationHistory.history_types[:comment_created],
      user: Current.user,
      previous_value: nil,
      new_value: "[id-#{id}] #{message}"
    )
  end

  def create_conversation_history_for_comment_update
    previous_message, new_message = saved_change_to_message

    project.project_conversation_histories.create!(
      history_type: ProjectConversationHistory.history_types[:comment_updated],
      user: Current.user,
      previous_value: "[id-#{id}] #{previous_message}",
      new_value: "[id-#{id}] #{new_message}"
    )
  end

  def create_conversation_history_for_comment_delete
    project.project_conversation_histories.create!(
      history_type: ProjectConversationHistory.history_types[:comment_deleted],
      user: Current.user,
      previous_value: "[id-#{id}] #{message}",
      new_value: "DELETED"
    )
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_project
  before_action :set_comment, only: %i[ new edit create update destroy ]
  before_action :authorize_comment

  # GET /comments or /comments.json
  def index
    @comments = @project.comments
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = @project.comments.build(comment_params)
    @comment.user = Current.user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to project_path(@project), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: [ @project, @comment ] }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to project_path(@project), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: [ @project, @comment ] }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to project_path(@project), notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_comment
      if params[:id].blank? # new?, create? TODO: a better fix?
        @comment = Comment.new(project_id: @project.id)
      else
        @comment = @project.comments.find(params[:id])
      end
    end

    def comment_params
      params.require(:comment).permit(:message)
    end

    def authorize_comment
      if @comment
        authorize @comment
      else
        authorize Comment
      end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [@project, comment], class: "contents") do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul class="list-disc ml-6">
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-4">
    <%= form.label :message, class: "block text-sm font-medium text-gray-700" %>
    <%= form.text_area :message,
        class: "mt-1 p-4 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50",
        rows: 4,
        placeholder: "Write your comment here..." %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/comments/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Comments#create</h1>
  <p>Find me in app/views/comments/create.html.erb</p>
</div>

app/views/comments/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Comments#destroy</h1>
  <p>Find me in app/views/comments/destroy.html.erb</p>
</div>

app/views/comments/edit.html.erb
<% content_for :title, "Editing comment" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing comment</h1>

  <%= render "form", comment: @comment %>

  <%= link_to "Back to comments", project_comments_path(@project), class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/comments/index.html.erb
<% content_for :title, "Comments" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="block flex justify-between items-center">
    <h1 class="font-bold text-4xl">Comments</h1>

    <div class="flex space-x-3">
      <%= link_to "New comment", new_project_comment_path(@project), class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium" %>
      <%= link_to "Back to Project", project_path(@project), class: "rounded-md px-3.5 py-2.5 bg-gray-400 hover:bg-gray-300 text-white inline-block font-medium" %>
    </div>
  </div>

  <div id="comments" class="min-w-full mt-4">
    <% if @comments.any? %>
      <% @comments.each do |comment| %>
        <hr class="border-gray-300 my-2">

        <div>
          <span>Comment by</span>
          <span class="font-bold"> <%= comment.user.email_address %> </span>
          <span>on</span>
          <span class="font-medium"> <%= comment.created_at.strftime("%Y-%m-%d %H:%M:%S") %></span>
        </div>
        <p class="text-xl text-gray-700 bg-gray-100 px-3 py-2 rounded-lg mt-2">
          <%= comment.message %>
        </p>

        <% if comment.user_id == Current.user.id %>
          <%= link_to "Edit this comment", edit_project_comment_path(@project, comment), class: "mt-2 rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 inline-block font-medium text-white" %>
        <% end %>

        <% if Current.user.admin? || comment.user_id == Current.user.id %>
          <div class="inline-block ml-2">
            <%= button_to "Delete this comment", project_comment_path(@project, comment), method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium" %>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <p class="text-center my-10">No comments found.</p>
    <% end %>
  </div>
</div>

app/views/comments/new.html.erb
<% content_for :title, "New comment" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New comment</h1>

  <%= render "form", comment: @comment %>

  <%= link_to "Back to project", project_path(@project), class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/comments/show.html.erb
<% content_for :title, "Showing comment" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing comment</h1>

  <%= render @comment %>

  <%= link_to "Edit this comment", edit_project_comment_path(@comment), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to project", project_path(@comment.project), class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/comments/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Comments#update</h1>
  <p>Find me in app/views/comments/update.html.erb</p>
</div>