config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :comments, except: :show
    resources :project_conversation_histories, only: :show
  end
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :manager_user, class_name: "User", optional: true, foreign_key: "manager_user_id"
  has_many :project_users
  has_many :users, through: :project_users
  has_many :project_conversation_histories
  has_many :comments

  validates :name, presence: true

  enum :status, [ :todo, :active, :completed ]

  after_update :create_status_change_conversation_history, if: :saved_change_to_status?

  private

  def create_status_change_conversation_history
    previous_status, new_status = saved_change_to_status

    project_conversation_histories.create!(
      history_type: ProjectConversationHistory.history_types[:project_status_update],
      user: Current.user,
      previous_value: previous_status,
      new_value: new_status
    )
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :authorize_project

  # GET /projects or /projects.json
  def index
    @projects = policy_scope(Project)
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      # Handle manager assignment
      if project_params[:manager_id].present?
        manager = User.manager.find_by(id: project_params[:manager_id])
        if manager
          @project.project_users.where(user: @project.users.manager).destroy_all
          @project.project_users.build(user: manager)
        end
      end

      if @project.update(project_params.except(:manager_id))
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy!

    respond_to do |format|
      format.html { redirect_to projects_path, status: :see_other, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :status, :description, :start_date, :end_date, :manager_user_id, user_ids: [])
    end

    def authorize_project
      if @project
        authorize @project
      else
        authorize Project
      end
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, class: "contents") do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul class="list-disc ml-6">
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": project.errors[:name].none?, "border-red-400 focus:outline-red-600": project.errors[:name].any?}] %>
  </div>

  <!-- TODO: status CSS needs some fix -->
  <div class="my-5">
    <%= form.label :status %>
    <%= form.select :status,
      Project.statuses.keys.map { |status| [status.humanize, status] },
      class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": project.errors[:status].none?, "border-red-400 focus:outline-red-600": project.errors[:status].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.textarea :description, rows: 4, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": project.errors[:description].none?, "border-red-400 focus:outline-red-600": project.errors[:description].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :start_date %>
    <%= form.datetime_field :start_date, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": project.errors[:start_date].none?, "border-red-400 focus:outline-blue-600": project.errors[:start_date].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :end_date %>
    <%= form.datetime_field :end_date, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": project.errors[:end_date].none?, "border-red-400 focus:outline-blue-600": project.errors[:end_date].any?}] %>
  </div>

  <!-- only allow admin users to assign project managers -->
  <% if Current.user.admin? %>
    <div class="my-5">
      <label class="block font-medium text-gray-700">Project Manager</label>
      <div class="mt-2 space-y-2">
        <% User.manager.each do |user| %>
          <div class="flex items-center">
            <%= form.radio_button :manager_user_id, user.id,
                id: "manager_#{user.id}",
                class: "h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300" %>
            <label for="manager_<%= user.id %>" class="ml-2 block text-sm text-gray-900">
              <%= user.email_address %>
            </label>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>

  <!-- allow admins and managers to assign project mmembers -->
  <% if Current.user.admin? || Current.user.manager? %>
    <div class="my-5">
      <label class="block font-medium text-gray-700">Project Members</label>
      <div class="mt-2 space-y-2">
        <% User.member.each do |user| %>
          <div class="flex items-center">
            <%= check_box_tag "project[user_ids][]", user.id,
                project.users.include?(user),
                id: "user_#{user.id}",
                class: "h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded" %>
            <label for="user_<%= user.id %>" class="ml-2 block text-sm text-gray-900">
              <%= user.email_address %>
            </label>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p class="my-3">
    <strong class="font-bold mb-1">Name:</strong>
    <%= project.name %>
  </p>
  <p class="my-3">
    <strong class="font-bold mb-1">Status:</strong>
    <%= project.status %>
  </p>
  <p class="my-3">
    <strong class="font-bold mb-1">Manager:</strong>
    <%= project.manager_user.email_address %>
  </p>
</div>

app/views/projects/edit.html.erb
<% content_for :title, "Editing project" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing project</h1>

  <%= render "form", project: @project %>

  <%= link_to "Show this project", @project, class: "rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to projects", projects_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/projects/index.html.erb
<% content_for :title, "Projects" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Projects</h1>
    <% if Current.user.admin? %>
      <%= link_to "New project", new_project_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
    <% end %>
  </div>

  <div id="projects" class="min-w-full">
    <% if @projects.any? %>
      <% @projects.each do |project| %>
        <%= link_to project do %>
          <div class="bg-gray-200 hover:bg-gray-300 px-3 py-0.5 rounded-md my-4">
            <%= render project %>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <p class="text-center my-10">No projects found. Ask your admin to assign you to projects.</p>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<% content_for :title, "New project" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New project</h1>

  <%= render "form", project: @project %>

  <%= link_to "Back to projects", projects_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/projects/show.html.erb
<% content_for :title, "Showing project" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing project</h1>

  <%= render @project %>

  <p class="my-3">
    <strong class="font-bold mb-1">Start date:</strong>
    <%= @project.start_date %>
  </p>
  <p class="my-3">
    <strong class="font-bold mb-1">End date:</strong>
    <%= @project.end_date %>
  </p>
  <p class="my-3">
    <strong class="block font-bold mb-1">Description:</strong>
    <%= @project.description.truncate(100) %>
  </p>

  <% if @project.users.count > 0 %>
    <strong class="block font-bold mb-1">Members:</strong>
    <% @project.users.each_with_index do |user, index| %>
      <p class="my-3">
        <%= "#{index+1}. #{user.email_address}" %>
      </p>
    <% end %>
  <% end %>

  <% if Current.user.admin? || (@project.manager_user_id == Current.user.id) %>
    <%= link_to "Edit this project", edit_project_path(@project), class: "mt-2 rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 inline-block font-medium text-gray-100" %>
  <% end %>

  <%= link_to "New Comment", new_project_comment_path(@project), class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 inline-block font-medium text-gray-100" %>
  <%= link_to "Show All Comments", project_comments_path(@project), class: "rounded-md px-3.5 py-2.5 bg-gray-300 hover:bg-gray-200 inline-block font-medium" %>

  <% if Current.user.admin? %>
    <div class="inline-block">
      <%= button_to "Delete this project", @project, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium" %>
    </div>
  <% end %>

  <% if @project.project_conversation_histories.present? %>
    <div class="text-center">
      <h2 class="text-4xl font-semibold text-gray-800 my-10">Conversation History (Latest First)</h2>

      <% @project.project_conversation_histories.reverse.each do |project_conv_history| %>
        <%= render "project_conversation_history/show", history: project_conv_history %>
      <% end %>
    </div>
  <% end %>
</div>